Repository rursprung/fhgr-sweng-pattern-recognition, pull requests merged in 2023-10, with the labels that each got.

#16 add csv file logger
  .gitignore
  src/app.py
  src/pattern_logger/csv_logger.py
Labels: enhancement

#20 add architecture diagram
  README.md
Labels: documentation

#21 only report new patterns
  README.md
  assets/test_image00.jpg
  assets/test_image01.jpg
  assets/test_image02.jpg
  assets/test_image03.jpg
  assets/test_image04.jpg
  src/app_stored_images/__init__.py
  src/app_stored_images/__main__.py
  src/app_stored_images/app.py
  src/image_proc/image_proc.py
  src/pattern_processor/__init__.py
  src/pattern_processor/pattern_filter.py
  src/single_image_proc/__main__.py
Labels: documentation, enhancement
