Repository rursprung/fhgr-sweng-pattern-recognition, pull requests merged in 2023-11, with the labels that each got.

#25 add video input
  README.md
  src/app.py
  src/app_stored_images/app.py
  src/app_webcam/__init__.py
  src/app_webcam/__main__.py
  src/app_webcam/app.py
Labels: enhancement

#26 fix python wheel distribution
  pyproject.toml
Labels: bug

#28 implement text to speech function
  README.md
  poetry.lock
  pyproject.toml
  src/app.py
  src/output/__init__.py
  src/output/pattern_logger/__init__.py
  src/output/pattern_logger/console_logger.py
  src/output/pattern_logger/csv_logger.py
  src/output/pattern_logger/pattern_logger.py
  src/output/tts/__init__.py
  src/output/tts/tts.py
  src/output/tts/tts_offline.py
  src/output/tts/tts_online.py
  src/output/visualizer/__init__.py
  src/output/visualizer/visualizer.py
Labels: enhancement

#29 extend README & adjust window title
  README.md
  src/app.py
Labels: documentation

#30 Allow closing the program with close button
  src/app.py
  src/output/tts/tts_online.py
  src/output/visualizer/visualizer.py
Labels: bug

#31 add docstrings & improve code readability
  src/app.py
  src/image_proc/image_proc.py
  src/output/pattern_logger/console_logger.py
  src/output/pattern_logger/csv_logger.py
  src/output/pattern_logger/pattern_logger.py
  src/output/tts/tts.py
  src/output/tts/tts_offline.py
  src/output/tts/tts_online.py
  src/output/visualizer/visualizer.py
  src/pattern_processor/pattern_filter.py
Labels: documentation

#33 fix variable renaming
  src/app.py
  src/image_proc/image_proc.py
Labels: bug

#34 Add static architecture diagram
  README.md
  src/image_proc/image_proc.py
Labels: documentation

#35 Application configuration using a config file
  README.md
  config/config.toml
  src/app.py
  src/config.py
  src/output/pattern_logger/csv_logger.py
  src/output/tts/tts.py
Labels: enhancement
